/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./../components/base-footer/index.vue')['default']
    BaseHeader: typeof import('./../components/base-header/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
  }
}
